// Generated by CoffeeScript 1.6.3
/*
jQuery Modal
Copyright 2013 Kevin Sylvestre
*/


(function() {
  "use strict";
  var $, Animation, Modal,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = jQuery;

  Animation = (function() {
    function Animation() {}

    Animation.transitions = {
      "webkitTransition": "webkitTransitionEnd",
      "mozTransition": "mozTransitionEnd",
      "msTransition": "msTransitionEnd",
      "oTransition": "oTransitionEnd",
      "transition": "transitionend"
    };

    Animation.transition = function($el) {
      var el, result, type, _ref;
      el = $el[0];
      _ref = this.transitions;
      for (type in _ref) {
        result = _ref[type];
        if (el.style[type] != null) {
          return result;
        }
      }
    };

    Animation.execute = function($el, callback) {
      var transition;
      transition = this.transition($el);
      if (transition != null) {
        return $el.one(transition, callback);
      } else {
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    return Animation;

  })();

  Modal = (function() {
    Modal.modal = function($el, options) {
      var data;
      if (options == null) {
        options = {};
      }
      data = $el.data('modal');
      if (!data) {
        data = new Modal($el, options);
        $el.data('modal', data);
      }
      return data;
    };

    Modal.prototype.$ = function(selector) {
      return this.$modal.find(selector);
    };

    function Modal($el, settings) {
      if (settings == null) {
        settings = {};
      }
      this.show = __bind(this.show, this);
      this.hide = __bind(this.hide, this);
      this.clear = __bind(this.clear, this);
      this.setup = __bind(this.setup, this);
      this.toggle = __bind(this.toggle, this);
      this.keyup = __bind(this.keyup, this);
      this.close = __bind(this.close, this);
      this.$ = __bind(this.$, this);
      this.$el = $el;
      this.$vignette = $("<div class='vignette'></div>");
      $(document.body).append(this.$vignette);
    }

    Modal.prototype.close = function(event) {
      if (event != null) {
        event.preventDefault();
      }
      if (event != null) {
        event.stopPropagation();
      }
      return this.hide();
    };

    Modal.prototype.keyup = function(event) {
      if (event.target.form != null) {
        return;
      }
      if (event.which === 27) {
        return this.close();
      }
    };

    Modal.prototype.toggle = function(method) {
      if (method == null) {
        method = 'on';
      }
      $(document)[method]("keyup", this.keyup);
      this.$vignette[method]("click", this.close);
      return this.$el[method]('click', '[data-dismiss="modal"]', this.close);
    };

    Modal.prototype.setup = function() {
      return this.toggle('on');
    };

    Modal.prototype.clear = function() {
      return this.toggle('off');
    };

    Modal.prototype.hide = function() {
      var alpha, omega,
        _this = this;
      alpha = this.clear;
      omega = function() {
        _this.$vignette.hide();
        return _this.$el.hide();
      };
      alpha();
      this.$el.position();
      this.$el.addClass('fade');
      return Animation.execute(this.$el, omega);
    };

    Modal.prototype.show = function() {
      var alpha, omega,
        _this = this;
      omega = this.setup;
      alpha = function() {
        _this.$vignette.show();
        return _this.$el.show();
      };
      alpha();
      this.$el.addClass('fade');
      this.$el.position();
      this.$el.removeClass('fade');
      return Animation.execute(this.$el, omega);
    };

    return Modal;

  })();

  $.fn.extend({
    modal: function(option) {
      if (option == null) {
        option = {};
      }
      return this.each(function() {
        var $this, action, options;
        $this = $(this);
        options = $.extend({}, $.fn.modal.defaults, typeof option === "object" && option);
        action = typeof option === "string" ? option : option.action;
        if (action == null) {
          action = "show";
        }
        return Modal.modal($this, options)[action]();
      });
    }
  });

}).call(this);
