// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    return $('.try').click(function(event) {
      event.preventDefault();
      event.stopPropagation();
      return $('.modal').modal();
    });
  });

}).call(this);
